config/routes.rb
Picturefight::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  devise_scope :user do
    root :to => 'registrations#new'
    get "/sign_out" => "devise/sessions#destroy", :as=>"sign_out"
  end
  resources :images,:only => [:index, :new, :create] do
    collection do
      get "hall_of_fame"
    end
  end
  resources :fights, :only=> [:index, :show], :as=>:fights do
    collection do
      post "start_fight"
      get "popular"
      get "closed"
    end
    member do
      resources :votes, :only => [:create]
    end
  end
  resources :users, :only=>[:show] do
    member do
      resources :images, :except => [:index, :new, :create]
      get "images" => "images#my"
      get "fights" => "fights#my"
    end
  end

  

end

app/models/fight.rb
class Fight < ActiveRecord::Base
  validate :has_uniq_images_among_fights?
  belongs_to :category
  belongs_to :player_1, class_name: "User"
  belongs_to :player_2, class_name: "User"
  belongs_to :player_1_image, class_name: "Image"
  belongs_to :player_2_image, class_name: "Image"
  has_many :comments
  has_many :votes
  belongs_to :winner, class_name: "User"

  scope :active_fights, -> { where("datetime_end > ?", DateTime.current).where("player_1_id is NOT NULL AND player_2_id is NOT NULL")}
  scope :closed_fights, -> { where("datetime_end <=?", DateTime.current)}



  def has_uniq_images_among_fights?
    found = Fight.where(:winner_id => nil).where("player_1_image_id IN (?, ?) OR player_2_image_id IN (?, ?)", player_1_image_id,player_2_image_id,player_1_image_id, player_2_image_id)
    ok = found.empty? || (found.size == 1 && found.first == self)
    errors.add(:base, "this picture already takes part in a fight.") if !ok
  end


end

app/controllers/fights_controller.rb
class FightsController < ApplicationController


  def index
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @fights = Fight.active_fights.where(category_id: category.id).order(created_at: :desc)
    else
      @fights = Fight.active_fights.order(created_at: :desc)
    end

    @active_place = "latest"
    @categories = Category.all
  end

  def my
    @owner = User.where(username: params[:id]).first
    @active_place = params[:id]
    if signed_in?
      @active_place = "my" if params[:id]==current_user.username
    end
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @fights = Fight.where("player_1_id=? OR player_2_id=?", current_user.id, current_user.id).where(category_id: category.id).order(created_at: :desc )
    else
      @fights=Fight.where("player_1_id=? OR player_2_id=?", @owner.id, @owner.id).order(created_at: :desc)
    end
    @categories = assign_categories(@owner)
  end

  def show
     @fight = Fight.find(params[:id])
     @player_1 = User.find(@fight.player_1_id)
     @player_1_image = Image.find(@fight.player_1_image_id)


     if @fight.player_2_id.present?
        @player_2 = User.find(@fight.player_2_id)
        @player_2_image = Image.find(@fight.player_2_image_id)

     if @fight.datetime_end <= DateTime.now
       @closed = true
       if @player_1_votes_number > @player_2_votes_number
         @winner = "The winner is "+@player_1.username.to_s
       elsif @player_1_votes_number == @player_2_votes_number
         @winner = "It is a draw !"
       else
         @winner = "The winner is "+@player_2.username.to_s
       end
     end

     end

     @allow_to_vote = false
     if signed_in?
       @vote = Vote.new(fight_id: @fight.id, user_id: current_user.id)
       @votes = Vote.where(fight_id: @fight.id)
       @allow_to_vote = true if @vote.valid?
     end
     @player_1_votes_number = @fight.votes.where(for_player_id: @fight.player_1_id).count
     @player_2_votes_number = @fight.votes.where(for_player_id: @fight.player_2_id).count


     @active_place = params[:id]
  end

  def popular
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @fights = Fight.active_fights.where(category_id: category.id).order(votes_count: :desc)
    else
      @fights = Fight.active_fights.order(votes_count: :desc)
    end

    @active_place = "popular"
    @categories = Category.all
    render :index
  end

  def closed
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @fights = Fight.closed_fights.where(category_id: category.id).order(votes_count: :desc)
    else
      @fights = Fight.closed_fights.order(votes_count: :desc)
    end

    @active_place = "closed"
    @categories = Category.all
    render :index
  end

  def start_fight

    image = current_user.images.find(params[:image])

    open_fight = Fight.where(winner_id: nil).where("player_1_id!=?", current_user.id).where(player_2_id: nil).where(category_id: image.category_id)

    if open_fight.present?
      @fight = open_fight.first
      @fight.player_2 = current_user
      @fight.player_2_image = image
      @fight.datetime_end = DateTime.now + 1


    else
      @fight = Fight.new
      @fight.category = image.category
      @fight.player_1 = current_user
      @fight.player_1_image = image

    end
    if @fight.save
        redirect_to @fight
    else
      redirect_to images_path(current_user), :alert => "Error adding this picture to the fight"
    end
  end


  def assign_categories(owner)
    category_rows = Fight.where("player_1_id=? OR player_2_id=?", owner.id, owner.id).select("distinct category_id")
    category_ids = category_rows.collect{ |a| a[:category_id]}
    categories = Category.find(category_ids)
    return categories
  end


end

app/helpers/fights_helper.rb
module FightsHelper
end

app/views/fights/_search_and_subnav.html.erb
<div class="sectionname">Fights/</div>
<div class="search">
  <ul>
    <%= form_tag("/search", method: "get") do %>
        <li><%= label_tag(:q, "Search for:") %></li>
        <li><%= text_field_tag(:q, "Type Keywords", :class=>"form-control") %></li>
        <li><%= submit_tag("Search", :class=>"btn btn-primary")%></li>
    <% end %>
  </ul>
</div>
<div class="subnavigation">
  <ul>
    <li><%= link_to("latest",  fights_path) %></li>
    <li><%= link_to("popular", popular_fights_path) %></li>
    <li><%= link_to("closed fights", closed_fights_path) %></li>
    <% if signed_in? %>
    <li><%= link_to("my fights", fights_user_path(current_user))%></li>
    <% end %>
  </ul>
</div>

app/views/fights/index.html.erb
<%= render "search_and_subnav" %>

<section class="show">
  <div class="subtitle">
    <h3>Fights / <%= @active_place %></h3>
  </div>
  <div class="insideshow">
    <div class="category">
      <h3>Categories / </h3>
      <ul>
        <li>
          <%= link_to("All") %></li>
        <% @categories.each do |category| %>
            <li><%= link_to(category.name.humanize.add_question_mark, "?category=#{category.name}") %></li>
        <% end %>
      </ul>
    </div>
    <section class="elements">
      <% @fights.each do |fight| %>
        <article>
          <div class="fight_element">
            <div><%= image_tag(fight.player_1_image.image_file.url(:medium), class:"img-responsive nicebackground") %></div>
            <div class="image_title"><%= fight.player_1_image.title %></div>
          </div>
          <div class="vs_index"> VS </div>
          <div class="fight_element">
            <div><%= image_tag(fight.player_2_image.image_file.url(:medium), class:"img-responsive nicebackground") %></div>
            <div class="image_title"><%= fight.player_2_image.title %></div>
          </div>
          <div class="show_fight"><%= link_to("Show Fight", fight_path(fight.id)) %></div>
        </article>


      <% end %>
      </section>
</div>
</section>

app/views/fights/my.html.erb
<%= render "search_and_subnav" %>

<section class="show">
  <div class="subtitle">
    <h3>Fights / <%= @active_place %></h3>
  </div>
  <div class="insideshow">
    <div class="category">
      <h3>Categories / </h3>
      <ul>
        <li>
          <%= link_to("All") %></li>
          <% @categories.each do |category| %>
            <li><%= link_to(category.name.humanize.add_question_mark, "?category=#{category.name}") %></li>
          <% end %>
      </ul>
    </div>
    <section class="elements">
      <% @fights.each do |fight| %>
          <article>
            <div class="fight_element">
              <div><%= image_tag(fight.player_1_image.image_file.url(:medium), class:"img-responsive nicebackground") %></div>
              <div class="image_title"><%= fight.player_1_image.title %></div>
            </div>
            <div class="vs_index"> VS </div>
            <% if fight.player_2.present? %>
              <div class="fight_element">
              <div><%= image_tag(fight.player_2_image.image_file.url(:medium), class:"img-responsive nicebackground") %></div>
              <div class="image_title"><%= fight.player_2_image.title %></div>
              </div>
            <% else %>
              <div class="fight_element">
              <div><%= image_tag("default_fight.jpg", class:"img-responsive nicebackground")%></div>
              <div class="image_title">waiting for opponent</div>
              </div>
            <% end %>
            <div class="show_fight"><%= link_to("Show Fight", fight_path(fight.id)) %></div>
          </article>
      <% end %>
    </section>
  </div>
</section>

app/views/fights/show.html.erb
<%= render "search_and_subnav" %>

<section class="show">
  <div class="subtitle">
    <h3>Fights / <%= @active_place %></h3>
  </div>
  <div class="insideshow">

    <section class="showelements">

          <article>
            <div class="big_fight_element">
                  <div class="player_username"><%= @player_1.username %></div>
                  <div><%= image_tag(@fight.player_1_image.image_file.url, class:"img-responsive nicebackground") %></div>
                  <div class="image_title"><%= @fight.player_1_image.title %></div>
              <% if @player_1.present? %>
                  <% if @allow_to_vote %>
                      <div><%= button_to("Vote",  votes_path(@fight)+"?for_player_id=#{@player_1.id}", :method => :post) %></div>
                  <% else %>
                      <div class="votes_number"><%=pluralize @player_1_votes_number, 'vote' %></div>
                  <% end %>
              <% end %>
            </div>
            <div class="vs_index"> VS </div>
            <div class="big_fight_element">
              <% if @player_2.present? %>
                  <div class="player_username"><%= @player_2.username %></div>
                  <div><%= image_tag(@fight.player_2_image.image_file.url, class:"img-responsive nicebackground") %></div>
                  <div class="image_title"><%= @fight.player_2_image.title %></div>
                  <% if @allow_to_vote %>
                      <div><%= button_to("Vote", votes_path(@fight)+"?for_player_id=#{@player_2.id}", :method => :post) %></div>
                  <% else %>
                      <div class="votes_number"><%=pluralize @player_2_votes_number, 'vote' %></div>
                  <% end %>
              <% else %>
              <div>Waiting for opponent</div>
              <div><%= image_tag("default_fight.jpg", class:"img-responsive")%></div>
              <% end %>
             </div>
            <% if @closed == true %>
                <div class="show_winner"><%= @winner %></div>
            <% end %>
          </article>
    </section>
  </div>
</section>