config/routes.rb
Picturefight::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  devise_scope :user do
    root :to => 'registrations#new'
    get "/sign_out" => "devise/sessions#destroy", :as=>"sign_out"
  end
  resources :images,:only => [:index, :new, :create] do
    collection do
      get "hall_of_fame"
    end
  end
  resources :fights, :only=> [:index, :show], :as=>:fights do
    collection do
      post "start_fight"
      get "popular"
      get "closed"
    end
    member do
      resources :votes, :only => [:create]
    end
  end
  resources :users, :only=>[:show] do
    member do
      resources :images, :except => [:index, :new, :create]
      get "images" => "images#my"
      get "fights" => "fights#my"
    end
  end

  

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image_file, :presence => true,
                       :content_type => { :content_type => "image/jpeg" },
                       :size => { :in => 0..5000.kilobytes}

  validates :title, length:{minimum: 5, maximum: 30}, :uniqueness => true


  belongs_to :user
  belongs_to :category



  def fight
    Fight.where("player_1_image_id = ? OR player_2_image_id = ?", self.id, self.id).first
  end


  attr_accessor :image_url


  def file_exist?
    FileTest.exist?(self.image_url)
  end

end

app/controllers/images_controller.rb
require "open-uri"
class ImagesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]



  def index
    @active_place = "currently fighting"
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @fights = Fight.active_fights.where(category_id: category.id)
    else
      @fights = Fight.active_fights
    end
      @images_player_1_ids = @fights.collect { |row| row[:player_1_image_id] }
      @images_player_2_ids = @fights.collect { |row| row[:player_2_image_id] }
      @images_ids = @images_player_1_ids + @images_player_2_ids
      @images = Image.find(@images_ids).reverse
      @categories = Category.all
  end

  def my
    @owner = User.where(username: params[:id]).first
    @active_place = params[:id]
    if signed_in?
      @active_place = "my" if params[:id]==current_user.username
    end
    if params[:category].present?
      category_name = params[:category]
      category = Category.where(name: category_name).first
      @images = @owner.images.where(category_id: category.id)
    else
      @images=@owner.images
    end
    assign_categories(@owner)
  end

  def new
    @active_place = "new"
    #redirect_to(new_image_path(current_user)) if params[:id]!=current_user.username
    @image=Image.new
    if params[:w] # just for show better view
      render partial: "new"
    end


  end

  def create
    params[:image][:user_id]=current_user.id
    @image=Image.new(image_params)
    @image_from_url = params[:image][:image_url].match(/(?i)\.(jpg|png|gif)\z/)
    @image.image_file = get_image_from_url(params[:image][:image_url]) if @image_from_url
    if @image.save
      render :show
    else render :new
    end

  end

  def show
    @image=Image.find(params[:id])

  end

  def hall_of_fame

  end


  def image_params
    params.require(:image).permit(:title, :description, :category_id, :user_id, :image_file, :image_url)
  end

  def get_image_from_url(url)
    begin
      open(url)
    rescue
      nil
    end
  end

  def assign_categories(owner)
    category_rows = owner.images.select("distinct category_id")
    category_ids = category_rows.collect { |a| a[:category_id] }
    @categories = Category.find(category_ids)
    return @categories
  end


end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_new.html.erb
<% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% @image.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@image, :html => { :multipart => true }) do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title , :class=>"form-control" %>
    </div>
    <div class="field">
      <%= f.label :category %>
      <select class="form-control" id="image_category_id" name="image[category_id]">
        <% Category.all.each do |category| %>
            <option value="<%= category.id %>"><%= category.name.humanize %> ?</option>
        <% end %>
      </select>

    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, :class=>"form-control" %>
    </div>
    <div class="field">
      <%= f.label :image_url %>
      <%= f.text_field :image_url, :class=>"form-control" %>
    </div>
    <div>or</div>
    <div class="field">
      <%= f.label "Upload from disk" %>
      <%= f.file_field :image_file %>
    </div>
    <div class="field addimage">
      <%= f.submit "Add", :class=>"btn btn-primary" %>
    </div>
<% end %>

app/views/images/_search_and_subnav.html.erb
<div class="sectionname">Images/</div>
<div class="search">
  <ul>
    <%= form_tag("/search", method: "get") do %>
        <li><%= label_tag(:q, "Search for:") %></li>
        <li><%= text_field_tag(:q, "Type Keywords", :class => "form-control") %></li>
        <li><%= submit_tag("Search", :class => "btn btn-primary") %></li>
    <% end %>
  </ul>
</div>
<div class="subnavigation">
  <ul>
    <% if signed_in?  %>
    <li><%= link_to("Add Image", new_image_path, :id=>"add_image")%></li>
    <% end %>
    <li><%= link_to("currently fighting", images_path) %></li>
    <li><%= link_to("hall of fame", hall_of_fame_images_path) %></li>
    <% if signed_in? %>
    <li><%= link_to("my images", images_user_path(current_user)) %></li>
    <% end %>
  </ul>
</div>

app/views/images/index.html.erb
<%= render "search_and_subnav" %>
<section class="show">
  <div class="subtitle">
    <h3>Images / <%= @active_place %></h3>
  </div>
  <div class="insideshow">
  <div class="category">
    <h3>Categories / </h3>
    <ul>
      <li><% link_to("All", "?") %></li>
      <% @categories.each do |category| %>
          <li><%= link_to(category.name.humanize.add_question_mark, "?category=#{category.name}") %></li>
      <% end %>
    </ul>
  </div>
  <section class="elements">
  <% @images.each do |image| %>
      <div class="image_element">
        <div>
          <%= link_to image_tag(image.image_file.url(:medium), class: "img-responsive nicebackground"), "/users/#{image.user_id}/images/#{image.id}" %>
        </div>
        <div class="image_title"><%= image.title %></div>
        <% if image.fight %>
            <div class="show_fight_in_images"><%= link_to("Show Fight", fight_path(image.fight)) %></div>
        <% end %>
      </div>
  <% end %>
  </section>
  </div>
</section>

app/views/images/my.html.erb
<%= render "search_and_subnav" %>
<section class="show">
  <div class="subtitle">
    <h3>Images / <%= @active_place %></h3>
  </div>
  <div class="insideshow">
  <div class="category">
    <h3>Categories / </h3>
    <ul>
      <li><% link_to("All", "?") %></li>
      <% @categories.each do |category| %>
          <li><%= link_to(category.name.humanize.add_question_mark, "?category=#{category.name}") %></li>
      <% end %>
    </ul>
  </div>
  <section class="elements">
  <% @images.each do |image| %>
      <div class="image_element">
        <div>
          <%= link_to image_tag(image.image_file.url(:medium), class: "img-responsive nicebackground"), "/users/#{image.user_id}/images/#{image.id}" %>
        </div>
        <div class="image_title"><%= image.title %></div>
        <% if @owner==current_user && image.fight == nil %>
            <div class="show_fight_in_images"><%= button_to("Start Fight", "/fights/start_fight?image=#{image.id}", method: :post ,:class => "btn btn-primary") %></div>
        <% elsif image.fight %>
            <div class="show_fight_in_images"><%= link_to("Fight Preview", fight_path(image.fight)) %></div>
        <% end %>
      </div>
  <% end %>
  </section>
  </div>
</section>

app/views/images/new.html.erb
<div class="form_edit_addimage">
  <h3>Add new image</h3>
    <%= render partial: "new" %>
</div>

app/views/images/show.html.erb
<%= render "search_and_subnav" %>
<section class="show">
  <div class="subtitle">
    <h3>Images / <%= @image.title %></h3>
  </div>
  <div class="insideshow">
      <div class="big_image_element">
        <div><%= image_tag(@image.image_file.url, class: "img-responsive nicebackground") %></div>
        <div class="image_title"><%= @image.title %></div>
      </div>
  </div>
</section>