config/routes.rb
Picturefight::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  devise_scope :user do
    root :to => 'registrations#new'
    get "/sign_out" => "devise/sessions#destroy", :as=>"sign_out"
  end
  resources :images,:only => [:index, :new, :create] do
    collection do
      get "hall_of_fame"
    end
  end
  resources :fights, :only=> [:index, :show], :as=>:fights do
    collection do
      post "start_fight"
      get "popular"
      get "closed"
    end
    member do
      resources :votes, :only => [:create]
    end
  end
  resources :users, :only=>[:show] do
    member do
      resources :images, :except => [:index, :new, :create]
      get "images" => "images#my"
      get "fights" => "fights#my"
    end
  end

  

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  belongs_to :achievement_db
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :images
   has_many :fights
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :fight
end

app/models/fight.rb
class Fight < ActiveRecord::Base
  validate :has_uniq_images_among_fights?
  belongs_to :category
  belongs_to :player_1, class_name: "User"
  belongs_to :player_2, class_name: "User"
  belongs_to :player_1_image, class_name: "Image"
  belongs_to :player_2_image, class_name: "Image"
  has_many :comments
  has_many :votes
  belongs_to :winner, class_name: "User"

  scope :active_fights, -> { where("datetime_end > ?", DateTime.current).where("player_1_id is NOT NULL AND player_2_id is NOT NULL")}
  scope :closed_fights, -> { where("datetime_end <=?", DateTime.current)}



  def has_uniq_images_among_fights?
    found = Fight.where(:winner_id => nil).where("player_1_image_id IN (?, ?) OR player_2_image_id IN (?, ?)", player_1_image_id,player_2_image_id,player_1_image_id, player_2_image_id)
    ok = found.empty? || (found.size == 1 && found.first == self)
    errors.add(:base, "this picture already takes part in a fight.") if !ok
  end


end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image_file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment :image_file, :presence => true,
                       :content_type => { :content_type => "image/jpeg" },
                       :size => { :in => 0..5000.kilobytes}

  validates :title, length:{minimum: 5, maximum: 30}, :uniqueness => true


  belongs_to :user
  belongs_to :category



  def fight
    Fight.where("player_1_image_id = ? OR player_2_image_id = ?", self.id, self.id).first
  end


  attr_accessor :image_url


  def file_exist?
    FileTest.exist?(self.image_url)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :username
  has_many :achievements
  has_many :images
  has_many :votes
  has_many :comments

  attr_accessor :current_password
  def fights
    Fight.where("player_1_id = #{self.id} OR player_2_id = #{self.id}")
  end

  def to_param
    username
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validate :added_vote?
  validate :member_of_fight?
  validate :two_players_presence?

  belongs_to :user
  belongs_to :fight, :counter_cache => true
  belongs_to :for_player, :class_name=>"User"
end

 def added_vote?
   found=Vote.where(fight_id: self.fight_id, user_id: self.user_id)
   ok = found.empty?
     errors.add(:base, "You have already voted in this fight .") if !ok
 end

 def member_of_fight?
   fight=Fight.find(self.fight_id)
   if fight.player_1_id == self.user_id || fight.player_2_id == self.user_id
     errors.add(:base, "You are the member of fight, you can't vote.")
   end
 end

def two_players_presence?
  fight=Fight.find(self.fight_id)
  unless fight.player_1 && fight.player_2
    errors.add(:base, "You can vote when fight has 2 players !")
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update

  end

  def to_param
    username
  end




end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def create
    @vote = Vote.new
    @vote.user = current_user
    @vote.fight_id = params[:id]
    @vote.for_player_id = params[:for_player_id]
    @vote.save
    redirect_to(fight_path(params[:id]))
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/all_fights_helper.rb
module AllFightsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Image Fight</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="/assets/javascript.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>


</head>
<body>
<div class="head_strap">
  <div class="information_strap">
    <ul>
      <li><img src="/assets/logo.png" alt="logo image fight" class="logo"/></li>
      <li><%= link_to("Image Fight", root_path)%></li>
    </ul>
    <div class="triangle-box">
      <div class="triangle-topleft"></div>
    </div>
  </div>
  <div class="account">

    <% unless user_signed_in? %>

        <%= form_for("user", :url => user_session_path, :method => "post") do |f| %>
              <ul>
              <li><%= f.email_field :email, :class => "form-control", :placeholder => "Email" %></li>
              <li><%= f.password_field :password, :class => "form-control", :placeholder => "Password" %></li>
              <li><%= f.submit "Sign in", :class => "btn btn-success", :value => "Sign in" %></li>
              <% if devise_mapping.rememberable? -%>
                  <li><%= f.check_box :remember_me %></li>
                  <li><%= f.label :remember_me %></li>
              <% end %>
              </ul>
            <% if request.env['PATH_INFO']!="/" %>
              <div class="float_right"><span>Don't have you account ? </span><%= link_to("Sign up", root_path) %></div>
            <% end %>
            <div class="float_right">Forget the password ?</div>
        <% end -%>
    <% else %>
          <ul>
          <li>Logged as : </li>
          <li><%= current_user.username || current_user.email %></li>
          <li><%= link_to("Settings", edit_user_registration_path) %></li>
          <li><%= link_to("Sign Out", sign_out_path, :method => :delete) %></li>
          </ul>
    <% end %>

  </div>
</div>
<div class="navigation">
  <ul>
    <li class="fighticon"><%= link_to("Fights", fights_path, :class => "navigation-menu") %></li>
    <li class="imageicon"><%= link_to("images", images_path, :class => "navigation-menu") %></li>
    <li class="howicon"><%= link_to("Hall Of Winners", images_path, :class => "navigation-menu") %></li>
  </ul>
</div>
<hr></hr>
<div class="maincontainer">
  <% if flash[:alert] %>
      <p class="alert alert-error "><%= flash[:alert] %> </p>
  <% end %>
  <% if flash[:error] %>
      <p class="alert alert-error"><%= flash[:error] %> </p>
  <% end %>
  <% if flash[:notice] %>
      <p class="alert alert-info"><%= flash[:notice] %> </p>
  <% end %>

      <%= yield %>

</div>

<!-- additional windows (popup) -->
<div class="modal fade" id="add_image_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Add new Image</h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<footer>
  <p>&copy; Radosław Maurer 2013</p>
</footer>
</body>
</html>